name: plexaverse_cli
description: Plexaverse CLI to add Flutter UI components into a project.
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.6.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

executables:
  plexaverse: plexaverse
