name: plexaverse_cli
description: A powerful CLI tool for faster flutter application development. Easily add pre-built widgets and functional screens to your Flutter projects.
version: 0.1.5
homepage: https://plexaverse.com
repository: https://github.com/plexaverse/plexaverse_cli
issue_tracker: https://github.com/plexaverse/plexaverse_cli/issues
documentation: https://github.com/plexaverse/plexaverse_cli#readme
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.6.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

executables:
  plexaverse: plexaverse
